module.exports = {
  content: ['./**/*.php', './src/**/*.{js,jsx,ts,tsx}'],
  safelist: [
    'icon-set-size',
    'icon-set-size-huge',
    'icon-set-size-huge-2',
    'icon-set-size-huge-3',
    'icon-set-size-type',
    'icon-set-size-type-2',
    'icon-set-size-type-3',
    'icon-set-size-type-small',
    'how-to-measure-pic',
    'primary-colour',
    'secondary-colour',
    'primary-colour-background',
    'paragraph-colour',
    'svg-icon-primary-colour',
    'svg-icon-secondary-colour',
    'nomargin',
    'nomargintop',
    'nomarginbottom',
    'margin1em',
    'icon-top-style',
    'top-style',
    'desktop',
    'mobile',
    'gradetable1',
    'custom-layout-col',
    'custom-layout-col-inverse',
    'custom-layout-col-hard',
    'side-by-side',
    'side-by-side-3',
    'indent',
    'margin-top-table',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#0f8eff',
        secondary: '#0075db',
        dark: '#232833',
        light: '#f9f9f9',
      },
      fontFamily: {
        lato: ['Lato', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
